name: Gym_Auto_Booking

on:
  workflow_dispatch:
  schedule:
    - cron: '50 5 * * 0'
    - cron: '50 9 * * 1'
    - cron: '0 12 * * 2'
    - cron: '55 11 * * 3'
    - cron: '20 4 * * 4'

jobs:
  automated-booking:
    runs-on: windows-latest

    env:
      SCRIPT_TIMEZONE: Asia/Qatar

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Get Day and Time
        id: get_datetime
        shell: powershell
        run: |
          $time = Get-Date
          $decimalTime = [math]::Round($time.Hour + ($time.Minute / 60) + 3, 2)
          $decimalTime
          echo "::set-output name=current_time::$decimalTime"

      - name: Date And Time
        run: |
          echo "Current Day: ${{ steps.get_datetime.outputs.current_day }}"
          echo "Current Hour: ${{ steps.get_datetime.outputs.current_hour }}"
          echo "Current Time: ${{ steps.get_datetime.outputs.current_time }}"

      - name: Run Gym Booking
        shell: powershell
        run: >
          python gym.py --pa ${{ secrets.PASS_ME }} --i ${{ secrets.ID_ME }} --ln ${{ secrets.ME_LAST_NAME }} --fn ${{ secrets.ME_FIRST_NAME }} --ca 'Male Fitness Room' --t {{ steps.get_datetime.outputs.current_time }} --fd 7
